### ISSUE TITLE
How to mark goal cells in maze files

### ISSUE THREAD

**Issue by Peque** [micromouseonline/mazefiles#9]
We already discussed this in #7, but I still wanted to discuss this a bit more (in a different issue to avoid polluting the other thread).

For what I see, starting cell and goal cells are a way of indicating what was known by the mouse before the exploration phase. That information may change depending on the competition.

This means:

- I do agree that all 4 cells in classic mazes should be marked with a "G", as that is the information you have, but no more (i.e.: you do not know about the walls around that area).
- It seems under the current Japan rules the goal area is fully specified. In this case I do agree all cells should be marked with a "G" too. But I am assuming no information is given about the walls around the goal area.
- It seems under old Japan rules the goal area was not specified, but only the entrance (is not that correct?). That is the case I was talking about when I said we should only mark a single cell for "old" half-size mazes. If that is the only information you had before exploration, then I think we should not add any extra "clues".
- You mentioned that under Taiwanesse rules both the area and the entrance is specified/provided. If that is the case, then I think not only we should mark all the area with "G"s, but maybe also we should add an indicator of "known cell", because you do know the walls around the goal area.

Known cells could be indicated with an `*` (or any other character) at the right of the cell tag. Starting cells would all have that indication, as the starting cell is always known (you not only know the position, but also the walls around it):

Example of a Taiwanese maze:

```
o---o---o---o---o---o---o---o---o
|                               |
o   o   o---o---o---o---o---o   o
|   |                           |
o   o---o---o---o---o---o---o   o
|   |         G*  G*  G*|       |
o   o   o---o   o   o   o   o---o
|   |   |   | G*  G*  G*|       |
o   o   o   o---o---o---o---o   o
|   |   |                   |   |
o   o   o---o   o---o---o   o   o
|   |                   |   |   |
o   o   o---o---o---o   o   o   o
| S*|   |               |       |
o---o---o---o---o---o---o---o---o
```

Old Japanese:

```
o---o---o---o---o---o---o---o---o
|                               |
o   o   o---o---o---o---o---o   o
|   |                           |
o   o---o---o---o---o---o---o   o
|   |         G         |       |
o   o   o---o   o   o   o   o---o
|   |   |   |           |       |
o   o   o   o---o---o---o---o   o
|   |   |                   |   |
o   o   o---o   o---o---o   o   o
|   |                   |   |   |
o   o   o---o---o---o   o   o   o
| S*|   |               |       |
o---o---o---o---o---o---o---o---o
```

New Japanese:

```
o---o---o---o---o---o---o---o---o
|                               |
o   o   o---o---o---o---o---o   o
|   |                           |
o   o---o---o---o---o---o---o   o
|   |         G   G   G |       |
o   o   o---o   o   o   o   o---o
|   |   |   | G   G   G |       |
o   o   o   o---o---o---o---o   o
|   |   |                   |   |
o   o   o---o   o---o---o   o   o
|   |                   |   |   |
o   o   o---o---o---o   o   o   o
| S*|   |               |       |
o---o---o---o---o---o---o---o---o
```

Pinging @tokoro10g in case they want to share their opinions. Also in case we (or rather I) misinterpreted the Japanese rules (I used Google Translate, so it is very likely my interpretation is wrong).

**Comment by micromouseonline** [comment]
OK, yes. The mazes should have no more than was known in advance. That said, they are historical mazes and new mazes would have a region marked. It really only makes a difference if the maze data is being used in a simulator or if it is re-created for practice. (Or those strange things people do when they want to show they could have run it faster if only . . . )

However, I don't think there is anything to be gained by adding another indicator for cells that are known in advance. That is actually only true of the start cell and is implicit in the rules. It does not need marking out in the maze. The Japan rules do not state there will be a single entrance and they do not state the relationship between the entrance and the goal area. Thus, all the goal cells are unknown.

The Taiwan goal is given as a region and there is one entrance. Again, the relationship is not stated so it is not possible to say which wall is the entrance. Also, the only reason they have a single entrance is that they have only one finish gate and some issues with the hardware. That could change in a heartbeat.

In practice, it may be worse because I think I have seen some notes that say the goal **wil*l* have posts and some that say the goal area will **not** have posts. That can make a big difference if the posts are essential for turning and you need to do more than run straight out of the goal. Guess how I know.

**Comment by Peque** [comment]
I only use the maze files in the simulator, hence my point of view. :innocent: 

Feel free to close this issue or leave it open in case someone, some day, wants to add something.

**Comment by micromouseonline** [comment]
Then, since any actual mazes you encounter will use the region definition, you might as well leave them all as regions so that your testing is more robust.

I will leave it open for a bit.

**Comment by Peque** [comment]
@micromouseonline Closing this. I agree it is not necessary to use any other special notation. Marking the whole area with `G`s should be enough. :+1:
